### ISSUE TITLE
Can i have the PHP file ?

### ISSUE THREAD

**Issue by nirmala1993** [samcroft/loading-data-into-ionic#1]
I tried with my PHP URL in your code but data is not coming. if you want i can push the code here.

**Comment by samcroft** [comment]
Which url are you referring to? Do you mean the url in the services.js file? Can you access the url directly in your browser? http://samcroft.co.uk/comics-app/comics?callback=JSON_CALLBACK

**Comment by nirmala1993** [comment]
Yes i want this PHP file. Please help me.

**Comment by nirmala1993** [comment]
Hii,

This is my PHP code : 

<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$host = "localhost";
$user = "Your Database";
$pw = "Password";
$db = "Select Db";
$con= new mysqli($host,$user,$pw,$db);
$statement = mysqli_query($con, "SELECT \* FROM people");
foreach($statement as $res)
{
 //echo $res['id'], "<br> ", $res['name'], " <br>", $res['username'],"<br>";
//echo json_encode($res);

//echo $_GET['JSON_CALLBACK']."(".json_encode($res).")";
$json=json_encode($res);
$jsonp_callback=isset($_GET['callback'])?$_GET['callback']:null;
print $jsonp_callback?"$jsonp_callback($json)":$json;
 }  
mysqli_close($con);
?>

Using this code i cant getting data from my database and same as data are not display in ng-repeat of html page. So please help me to find out what errors is occur in this code. And tell me about what i do for display the data of database in ng-repeat of div tag.

**Comment by samcroft** [comment]
It looks like you have quite a lot of problems in your php. You should have a look at the php docs for mysqli - http://php.net/manual/en/mysqli-result.fetch-assoc.php

This is untested, but try something like:

``` php
$link = mysqli_connect("localhost", "username", "password", "database");

$query = "SELECT * FROM people";

if ($result = mysqli_query($link, $query)) {
    $rows = mysqli_fetch_assoc($result);

    $json = json_encode($rows);

    if (isset($_GET['JSON_CALLBACK'])) {
        echo sprintf('%s(%s)', $_GET['JSON_CALLBACK'], $json);
    } else {
        echo $json;
    }
}
```
